[versions]
netty = "4.2.0.Final"
snappy = "1.1.10.7"
snakeyaml = "2.3"
micrometer = "1.14.2"
slf4j = "2.0.16"
log4j = "2.24.3"
lombok = "1.18.36"
junit = "5.11.4"
mockito = "5.14.2"

[libraries]
netty-all = { group = "io.netty", name = "netty-all", version.ref = "netty" }
netty-transport = { group = "io.netty", name = "netty-transport", version.ref = "netty" }
netty-transport-epoll = { group = "io.netty", name = "netty-transport-native-epoll", version.ref = "netty" }
netty-transport-kqueue = { group = "io.netty", name = "netty-transport-native-kqueue", version.ref = "netty" }
netty-handler = { group = "io.netty", name = "netty-handler", version.ref = "netty" }
netty-codec = { group = "io.netty", name = "netty-codec", version.ref = "netty" }
netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }

snappy = { group = "org.xerial.snappy", name = "snappy-java", version.ref = "snappy" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }

micrometer-core = { group = "io.micrometer", name = "micrometer-core", version.ref = "micrometer" }
micrometer-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version.ref = "micrometer" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.11.4" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

[bundles]
netty = ["netty-transport", "netty-handler", "netty-codec", "netty-buffer"]
logging = ["slf4j-api", "log4j-slf4j2", "log4j-core"]
metrics = ["micrometer-core", "micrometer-prometheus"]
testing = ["junit-jupiter", "junit-platform-launcher", "mockito-core", "mockito-junit"]
